# Generated by Django 3.2 on 2022-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_hello_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='base_64',
            field=models.CharField(blank=True, default='', max_length=500000),
        ),
    ]
