# Generated by Django 3.2 on 2022-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_hello_base_64'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='buttom_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hello',
            name='buttom_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
