# Generated by Django 3.2 on 2022-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_section_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_1',
            name='base_64',
        ),
        migrations.AddField(
            model_name='section_1',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='section_1',
            name='base_64_background_image',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='section_1',
            name='base_64_image',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
    ]
