# Generated by Django 3.2 on 2022-06-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('testApp', '0010_auto_20220616_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_3',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testapp_section_3', serialize=False, to='cms.cmsplugin')),
                ('title_1', models.CharField(blank=True, max_length=50)),
                ('description_1', models.CharField(blank=True, max_length=1000)),
                ('title_2', models.CharField(blank=True, max_length=50)),
                ('description_2', models.CharField(blank=True, max_length=1000)),
                ('buttom_text', models.CharField(blank=True, max_length=50)),
                ('buttom_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('base_64_image', models.CharField(blank=True, default='', max_length=1000000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='section_1',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='section_1',
            name='base_64_background_image',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='section_1',
            name='base_64_image',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='section_1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
