# Generated by Django 3.2 on 2022-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_auto_20220616_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_4',
            name='image_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section_4',
            name='link_video',
            field=models.URLField(blank=True, max_length=10000),
        ),
    ]
