# Generated by Django 3.2 on 2022-06-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_section_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_5',
            name='text_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='section_5',
            name='link',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
