# Generated by Django 3.2 on 2022-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0015_auto_20220616_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_5',
            name='base_64_image_2',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='section_5',
            name='base_64_image_3',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='section_5',
            name='description_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='description_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='icon_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='section_5',
            name='icon_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='section_5',
            name='link_2',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='link_3',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='text_link_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='text_link_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='section_5',
            name='title_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='section_5',
            name='title_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
