# Generated by Django 3.2 on 2022-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0016_auto_20220616_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_5',
            name='base_64_image_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='base_64_image_3',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='icon_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='icon_3',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='text_link_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='text_link_3',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='section_5',
            name='title_3',
        ),
    ]
