# Generated by Django 3.2 on 2022-06-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('testApp', '0017_auto_20220616_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_6',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testapp_section_6', serialize=False, to='cms.cmsplugin')),
                ('check_box', models.BooleanField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_1', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_2', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_3', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_4', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_5', models.CharField(blank=True, max_length=50, null=True)),
                ('list_line_6', models.CharField(blank=True, max_length=50, null=True)),
                ('text_link', models.CharField(blank=True, max_length=1000)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('users_text', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
