# Generated by Django 3.2 on 2022-06-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('testApp', '0018_section_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_7',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testapp_section_7', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('base_64_image', models.CharField(blank=True, default='', max_length=1000000, null=True)),
                ('base_64_background_image', models.CharField(blank=True, default='', max_length=1000000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
