# Generated by Django 3.2 on 2022-06-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0019_section_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_7',
            name='buttom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section_7',
            name='buttom_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section_3',
            name='buttom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section_3',
            name='buttom_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
