# Generated by Django 3.2 on 2022-06-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('testApp', '0020_auto_20220617_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_8',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testapp_section_8', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text_link_1', models.CharField(blank=True, max_length=1000)),
                ('link_1', models.URLField(blank=True, max_length=2000)),
                ('text_link_2', models.CharField(blank=True, max_length=1000)),
                ('link_2', models.URLField(blank=True, max_length=2000)),
                ('text_link_3', models.CharField(blank=True, max_length=1000)),
                ('link_3', models.URLField(blank=True, max_length=2000)),
                ('text_link_4', models.CharField(blank=True, max_length=1000)),
                ('link_4', models.URLField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
